export const LOG_IN = "LOG_IN"
export const LOG_OUT = "LOG_OUT"
export const SIGN_UP = "SIGN_UP"

// USER ACTIONS
export const RISE_TICKET = "RISE_TICKET"
export const GET_USER_TICKETS = "GET_USER_TICKETS"
export const UPDATE_USER = "UPDATE_USER"

//STAFF ACTIONS
export const GET_ALL_TICKETS = "GET_ALL_TICKETS"
export const UPDATE_TICKET = "UPDATE_TICKET"
export const GET_ALL_AND_SEARCH_TICKETS = "GET_ALL_AND_SEARCH_TICKETS"

//SEARCH BAR
export const SEARCH_BY_ID = "SEARCH_BY_ID"
export const SEARCH_BY_NAME = "SEARCH_BY_NAME"

// USER // STAFF
export const GET_TICKET_DETAIL= "GET_TICKET DETAIL"








